CREATE SCHEMA Population;

CREATE TABLE Population.POPULATION (
  ID          NUMBER(9)      NOT NULL,
  NAME        VARCHAR2(32)   NOT NULL,
  DESCRIPTION VARCHAR2(1024) NOT NULL,
  CONSTRAINT PK_POPULATION PRIMARY KEY (id)
);